config/routes.rb
Rails.application.routes.draw do

  root                  'static_pages#landing'
  get     '/blog'	 => 'posts#index'
  get     '/signup'  => 'users#new'
  get     '/login'   => 'sessions#new'
  post    '/login'   => 'sessions#create'
  get	  '/logout'  => 'sessions#destroy'
  
  resources :posts do
    resources :comments
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	validates_presence_of :post_id
	validates_presence_of :name
	validates_presence_of :body
end

app/models/concerns/will_paginate.rb
WillPaginate.per_page = 10

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, dependent: :destroy
    per_page = 10

	validates_presence_of :title
	validates_presence_of :body

    def timestamp
        created_at.strftime('%d %B %Y %H:%M:%S')
    end
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :remember_token
  	before_save { self.email = email.downcase }


	validates :name, presence: true, length: {maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 255}, 
					  format: { with: VALID_EMAIL_REGEX },
					  uniqueness: { case_sensitive: false }

	has_secure_password
	validates :password, length: { minimum: 6 }

	# Returns the hash digest of the given string.
	def User.digest(string)
	  cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  	BCrypt::Engine.cost
	  BCrypt::Password.create(string, cost: cost)
  	end

	# Returns a random token.
 	  def User.new_token
      SecureRandom.urlsafe_base64
  	end

	# Remembers a user in the database for use in persistent sessions.
  	def remember
    	self.remember_token = User.new_token
    	update_attribute(:remember_digest, User.digest(remember_token))
  	end

  	# Returns true if the given token matches the digest.
  	def authenticated?(remember_token)
  		return false if remember_digest.nil?
    	BCrypt::Password.new(remember_digest).is_password?(remember_token)
  	end

	# Forgets a user.
  	def forget
    	update_attribute(:remember_digest, nil)
  	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @post, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
        format.js #create.js.erb
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:post_id, :body, :name)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.paginate(page: params[:page], per_page: 15).order('created_at DESC')
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find_by_id(params[:id])
  end

  # GET /posts/new
  def new
    if logged_in?
      @post = Post.new
    else
      redirect_to login_path
    end
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)

    if user && user.authenticate(params[:session][:password])
      log_in user
      remember user
      redirect_to '/posts'
    else
	  flash.now[:danger] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end

  end

  def destroy
  	log_out if logged_in?
  	redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def landing
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns the current logged-in user (if any).
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
  	forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<%= div_for comment do %>
<p>
	<strong>Posted <%= time_ago_in_words(comment.created_at) %></strong> <br>
	<%= h(comment.name) %> <br>
	<%= h(comment.body) %>
</p>
<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.number_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
 var new_comment = $("<%= escape_javascript(render(:partial => @comment)) %>").hide();
 $('#comments').prepend(new_comment);
 $('#comment_<%= @comment.id %>').fadeIn('slow');
 $('#new_comment')[0].reset();

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<body>
	    <div class="container">
		<%= yield %>
		</div>
	</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <!-- Actual form -->
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div>
  <h2><%= link_to post.title, post_path(post) %></h2>

  <small><em><%= post.timestamp %></em></small>

  <p><%= truncate(strip_tags(post.body), length: 600) %></p>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html>

<head>
 <meta charset="utf-8">
 <%= stylesheet_link_tag "css/style.css" %>
 <title>Senses UnB</title>
</head>

<p id="back-top">
<a href="#top"><span></span>voltar ao topo</a>
<p>

<body>
  <%= javascript_include_tag "application" %>
   <div id="menu">
    <div class="wrapper">
      <div class="navigation">
      <a href="/#about">quem somos</a>
      <a href="/#team">nossa equipe</a>
      <a href="/#join">como participar</a>
      <a href="/#contact">contato</a>
      <% if logged_in? %>
      <a> LOGGED</a>
      <% end %>
      </div>
    </div>
  </div> 

  <div class="welcome">
    <% if logged_in? %>
      <p id="new-post">
        <a href='posts/new'><span></span>novo post</a>
      </p>
    <% end %>
  </div>

  <div class="wrapper">
    <div class="posts-index" id="posts-index">
      <%= render @posts %>
    </div>

    <% if @posts.next_page %>
      <div id="infinite-scrolling">
        <%= will_paginate %>
      </div>
    <% end %>
  </div>
</body>

app/views/posts/index.js.erb
var delimiter = $('<div class="page-delimiter" data-page="<%= params[:page] %>"></div>');
$('#posts-index').append(delimiter);
$('#posts-index').append('<%= j render @posts %>');
$('.pagination').replaceWith('<%= j will_paginate @posts %>');
preparePagination(delimiter);
<% unless @posts.next_page %>
$('#infinite-scrolling .pagination').remove();
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h1><%= @post.title %></h1>
</p>

<p>
  <%= @post.body.html_safe %>
</p>

<hline>

<tr class="post">
  <td><%= @post.title %></td>
  <td><%= @post.body %></td>
  <td><%= link_to 'Show', @post %></td>
</tr>

<h3>Comments</h3>
<div id="comments">
    <%= render :partial => @post.comments.reverse %>
</div>

<%= form_for([@post, Comment.new], remote: true) do |f| %>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<br><br>
<% if logged_in? %>
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' } %> |
<% end %>
<%= link_to 'Back', posts_path %>

app/views/static_pages/about.html.erb
<% provide(:title, "O que é o quê?") %>
<h1>O que é o quê?</h1>
<p>
<h2>Capítulo Estudantil EMBS-UnB</h2>
<br>
Somos um grupo com três eixos e tal. Nam condimentum iaculis dui, sed fermentum erat feugiat in. Quisque felis nisl, molestie nec lobortis non, faucibus ac nisi. In in vehicula lectus, efficitur placerat lectus. Suspendisse in posuere risus. Curabitur vulputate, nisl laoreet rutrum efficitur, nunc ligula rutrum nunc, non consectetur mauris ex in metus. Sed id nunc eros. Nunc fermentum enim sed purus aliquam gravida. Aenean mollis libero sit amet quam accumsan, nec lobortis nulla consectetur. Curabitur tristique nunc erat. Aliquam dignissim sapien neque, non eleifend enim porttitor a.<br>
<br>
Maecenas facilisis eros dolor. Vestibulum ultrices tempus accumsan. Suspendisse et dolor nec dui porttitor viverra. Fusce condimentum fermentum pulvinar. Quisque ultrices massa nec leo egestas interdum. Proin euismod consequat nisl, mattis scelerisque sapien elementum sed. Donec eget sem a leo condimentum dignissim eget quis augue. Nulla sit amet arcu convallis, volutpat lectus in, finibus odio.<br>
<br>
<h2>EMBS – Engineering in Medicine and Biology Society</h2>
<br>
O IEEE tem várias sociedades temáticas, a EMBS é uma delas etc. Praesent tempus sem augue, ac posuere neque interdum sed. Pellentesque varius ligula nec malesuada vehicula. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris tristique ante viverra, sollicitudin magna a, suscipit enim. In tempus ex eu enim pulvinar, eu tristique felis venenatis. Nulla imperdiet fringilla lorem ut vehicula. Morbi et semper turpis. Sed ornare sed ipsum a sodales. Donec a pellentesque odio, ut aliquam turpis. Ut mollis facilisis lectus, ac dignissim ante euismod nec. Aliquam lacinia nisi vitae molestie iaculis. Donec maximus tempor orci non consequat. Proin tincidunt iaculis malesuada. Sed vitae nisi hendrerit, fermentum lectus ut, placerat lorem. Cras dignissim tellus justo, eget venenatis ligula tempor vel. Curabitur euismod turpis eu egestas venenatis.<br>
<br>
<h2>IEEE – Institute of Electrical and Electronics Engineers Society</h2>
<br>
O IEEE é um dos maiores institutos e tal. Padrões, artigos, conferências, etc. Inclusive Capítulos Estudantis. Ut ultrices, quam eu tempor dictum, dolor odio fermentum neque, sed tristique odio nisi vel lorem. Fusce venenatis eget quam ut maximus. Donec non lacus ut augue gravida imperdiet. Nunc in eros ligula. Maecenas posuere venenatis vehicula. Aliquam at odio laoreet, commodo felis non, tincidunt nunc. Mauris suscipit metus lorem, in consectetur leo eleifend a.<br>
<br>
Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus quis ex nunc. Sed eu ipsum tortor. Proin id sapien odio. In hac habitasse platea dictumst. Quisque viverra sodales felis ac consequat. Etiam ornare urna vitae euismod euismod. Aenean suscipit feugiat ligula non bibendum. Quisque tempor nisi a tellus mollis, sit amet luctus arcu molestie. Morbi quis eros tempus, hendrerit lorem id, convallis diam. Sed a tincidunt velit. Nullam pellentesque, neque eget rhoncus pellentesque, sem metus imperdiet nisi, ac placerat urna erat id eros.
</p>

app/views/static_pages/landing.html.erb
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <%= stylesheet_link_tag "css/style.css" %>
  <title>Senses UnB</title>
</head>

<body>
  <p id="back-top">
    <a href="#top"><span></span>voltar ao topo</a>
  </p>

 <%= javascript_include_tag "application" %>
 <div id="menu">
  <div class="wrapper">
   <div class="navigation">
    <a class="smooth-href" href="#about">quem somos</a>
    <a class="smooth-href" href="#team">nossa equipe</a>
    <a class="smooth-href" href="#join">como participar</a>
    <a class="smooth-href" href="#contact">contato</a>
    <!-- <a href="/blog">blog</a> -->
    <% if logged_in? %>
      <a> LOGGED</a>
    <% end %>
   </div>
  </div>
 </div>

 <div id="welcome">
  <div class="logo">
   <div class="calling">
    <b>O futuro da saúde é agora<br></b> e está sendo feito por todos nós,
    <br> em todos os lugares.
   </div>
  </div>
 </div>

 <div id="about">
  <div class="title">
   <div class="wrapper">
    <h1><b>quem</b>somos?</h1>
   </div>
  </div>
  <div class="wrapper first">
   <div class="column-3 italic">
    Somos o Capítulo de Engenharia Biomédica da Universidade de Brasília, trazendo para você oportunidades e informações acerca da Engenharia Biomédica no mundo e em Brasília.
   </div>
   <div class="column-3">
    <h2>O quê?</h2>
    <p>A Senses, antes de tudo, é um conglomerado de apaixonados. Apaixonados pela ideia de transformar vidas, por meio da inovação pautada na harmonia entre as diversas áreas de conhecimento que a Engenharia Biomédica coleciona.</p>
    <p>Transformando e adaptando os sentidos humanos, a Senses quer levar a iniciativa biomédica para o dia a dia, para os corredores da Universidade, somando esforços de alunos, professores e membros da comunidade local afim de levantar o estandarte: O
     futuro da saúde é agora e está sendo feito por todos nós, em todos os lugares.</p>
   </div>
   <div class="column-3">
    <h2>Como?</h2>
    <p>A Senses se baseia sobre 3 pilares fundamentais de trabalho. Nós almejamos o desenvolvimento de tecnologias assistivas, healthcare e transumanistas, contando com o trabalho colaborativo de estudantes e professores afim de construir produtos reais
     para a nossa comunidade e a comunidade global, sempre deixando nosso conhecimento acessível na internet.</p>
    <p>Dessa forma, nós queremos atingir o desenvolvimento acadêmico, tendo como norte a responsabilidade social que nosso trabalho exige, e somando a nossa força àqueles que já produzem conhecimento e aos que desejam dedicar-se ao mesmo propósito.</p>
   </div>
  </div>
 </div>
 </div>

 <div class="icons">
  <div class="wrapper">
   <div class="icon one">
    <div class="descript">
     desenvolvimento de tecnologias assistivas, healthcare e transumanistas
    </div>
   </div>
   <div class="icon two">
    <div class="descript">
     construir produtos reais para a nossa comunidade e a comunidade global
    </div>
   </div>
   <div class="icon three">
    <div class="descript">
     trabalho colaborativo de estudantes e professores
    </div>
   </div>
  </div>
 </div>

 <div id="about-ieee">
  <div class="wrapper first">
   <div class="column-3">
    <h2>O IEEE</h2>
    <p>Hoje, o Instituto de Engenheiros Eletricistas e Eletrônicos é o maior do mundo em número de sócios. Desde sua criação, em 1963, o IEEE configura um padrão internacional para códigos e normas em diversas áreas. Reúne também uma coleção enorme de artigos e editoriais sobre o que se desenvolve pelo mundo.</p>
     <p>Mas, sem sombra de dúvidas, o impacto mais direto e perceptível por nós é a grande participação do instituto nas universidades ao redor do mundo. Com Capítulos e Clubes que se dedicam a temas específicos, o IEEE tem sido um grande incentivador de inovação entre alunos de diversas áreas.</p>
   </div>
   <div class="column-3">
    <h2>A EMBS</h2>
    <p>A sociedade EMBS, Engineering in Medical and Biology Society, é hoje a maior comunidade global focada em Engenharia Biomédica. Presente em mais de 97 países, ela promove conhecimento e integração de apaixonados, além de fomentar ideias ao redor de todo o mundo.</p>
   </div>
   <div class="column-3">
    <div class="ieee">
    </div>
   </div>
  </div>
 </div>
<div id="team">
 <div class="title">
  <div class="wrapper">
   <h1>um conglomerado <br>de <b>apaixonados</b></h1>
  </div>

  <div class="wrapper first">
   <div class="member" id="amanda">
    <div class="name">
     <b>Amanda</b><br> hardware
    </div>
   </div>

   <div class="member" id="camila">
    <div class="name">
     <b>Camila</b><br> software
    </div>
   </div>

   <div class="member" id="cris">
    <div class="name">
     <b>Cris</b><br> software
    </div>
   </div>

   <div class="member" id="daniel">
    <div class="name">
     <b>Daniel</b><br> nãolembro:(
    </div>
   </div>

   <div class="member" id="levy">
    <div class="name">
     <b>Levy</b><br> conselheiro
    </div>
   </div>

   <div class="member" id="malu">
    <div class="name">
     <b>Malu</b><br>design
    </div>
   </div>

   <div class="member" id="raquel">
    <div class="name">
     <b>Raquel</b><br>design
    </div>
   </div>

   <div class="member" id="pedro">
    <div class="name">
     <b>Pedro</b><br>?????
    </div>
   </div>

   <div class="member" id="iracema">
    <div class="name">
     <b>Iracema</b><br>?????
    </div>
   </div>

   <div class="member" id="carol">
    <div class="name">
     <b>Carol</b><br>design
    </div>
   </div>

   <div class="member" id="andre">
    <div class="name">
     <b>Andre</b><br>?????
    </div>
   </div>

   <div class="member" id="lorens">
    <div class="name">
     <b>Lorens</b><br>Software
    </div>
   </div>

   <div class="member" id="natalia">
    <div class="name">
     <b>Natália</b><br>?????
    </div>
   </div>

   <div class="member" id="giovanna">
    <div class="name">
     <b>Giovanna</b><br>design
    </div>
   </div>

 </div>
</div>
</body>

</html>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>